[workspace]
members = [
    "day1",
    "day1/part2",
    "day2",
    "day2/p1",
    "day2/p2",
    # USE THIS NAMING CONVENTION PLS TNX
    "day3",
    "day3/day3p1",
    "day3/day3p2",
    "day4",
    "day4/day4p1",
    "day4/day4p2",
    "day5",
    "day5/day5p1",
    "day5/day5p2"
]
