[workspace]
members = [
    "day1",
    "day1/part2",
    "day2",
    "day2/p1",
    "day2/p2",
    # USE THIS NAMING CONVENTION PLS TNX
    "day3",
    "day3-p1",
    "day3-p2",
    "day4",
    "day4-p1",
    "day4-p2"
]
