[package]
name = "day5p2"
version = "0.1.0"
authors = ["Tristan Zander <knavetnz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day5 = { path = "../../day5" }
